export enum ErrorType {
    STRING_EOL_ERR,
    STRING_EOF_ERR,
    STRING_LEN_ERR,
    IDENT_LEN_ERR,
    NUM_PREC_ZERO_ERR,
    DOUBLE_EXC_VAL_ERR,
    INTEGER_EXC_VAL_ERR,
    OPERATOR_PARSE_ERR,
    UNREC_TOKEN_ERR,
    NEWLINE_ERR,
    PATH_ERR,
    INVALID_TOKEN_ERR,
    PARAMS_LEFT_BRACE_ERR,
    PARAMS_RIGHT_BRACE_ERR,
    PARAMS_COMMA_ERR,
    PARAM_NAME_ERR,
    FUN_BLOCK_ERR,
    FUN_IDENTIFIER_ERR

}

export enum WarningType {
    STRING_ESC_WARN
}
